// Bulk CBSE chapter→concept mappings (Classes 6–12), authored as CSV and
// parsed at load. This is the broad baseline that attaches diagrams to chapters
// across the syllabus; the curated DEFAULT_MAPPINGS (richer keywords/formulas)
// take precedence where they overlap, and admin overrides win over everything.
//
// Columns: classLevel,subject,chapter,synonyms,concepts,keywords,formulas,experiments
// (list fields are pipe-separated). Chapters containing commas are quoted.

import { parseCsv } from "./mappingCsv";
import { chapterKey, type ChapterMapping } from "./chapterConcepts";

const CSV = `classLevel,subject,chapter,synonyms,concepts,keywords,formulas,experiments
CLASS_6,SCIENCE,Separation of Substances,separation techniques,handpicking|winnowing|sedimentation|decantation|filtration|evaporation,,,
CLASS_6,SCIENCE,Electricity and Circuits,,circuit-simple,,,
CLASS_6,SCIENCE,Fun with Magnets,magnets,bar-magnet-field,,,
CLASS_6,SCIENCE,"Light, Shadows and Reflections",,reflection-laws,,,
CLASS_6,SCIENCE,Getting to Know Plants,,leaf|root-structure|flower-structure,,,
CLASS_7,SCIENCE,Light,,concave-mirror|convex-mirror|ray-diagram-lens|reflection-laws,,,
CLASS_7,SCIENCE,Electric Current and Its Effects,,circuit-simple|electromagnet,,,
CLASS_7,SCIENCE,Respiration in Organisms,,respiratory-system,,,
CLASS_7,SCIENCE,Transportation in Animals and Plants,,human-heart,,,
CLASS_7,SCIENCE,Nutrition in Plants,,photosynthesis|leaf,,,
CLASS_7,SCIENCE,"Acids, Bases and Salts",,ph-scale,,,
CLASS_7,MATHEMATICS,The Triangle and Its Properties,,right-triangle,,,
CLASS_8,SCIENCE,Cell — Structure and Functions,cell,plant-cell|animal-cell|cell-diagram,,,
CLASS_8,SCIENCE,Sound,,wave-transverse,,,
CLASS_8,SCIENCE,Chemical Effects of Electric Current,,circuit-simple|electrolysis,,,
CLASS_8,SCIENCE,Light,,human-eye|ray-diagram-lens,,,
CLASS_8,MATHEMATICS,Introduction to Graphs,,xy-graph|coordinate-plane,,,
CLASS_9,SCIENCE,Matter in Our Surroundings,,molecular-pure-mixture,,,
CLASS_9,SCIENCE,Is Matter Around Us Pure,pure substances and mixtures,molecular-pure-mixture|filtration|evaporation|crystallisation|sublimation|magnet-separation|chromatography|beaker-solution,,,
CLASS_9,SCIENCE,Atoms and Molecules,,atom-bohr,,,
CLASS_9,SCIENCE,Structure of the Atom,,atom-bohr,,,
CLASS_9,SCIENCE,The Fundamental Unit of Life,cell,plant-cell|animal-cell|cell-diagram,,,
CLASS_9,SCIENCE,Motion,,xy-graph,,,
CLASS_9,SCIENCE,Sound,,wave-transverse,,,
CLASS_9,MATHEMATICS,Coordinate Geometry,,coordinate-plane,,,
CLASS_9,MATHEMATICS,Linear Equations in Two Variables,,linear-equation-graph|coordinate-plane,,,
CLASS_9,MATHEMATICS,Triangles,,similar-triangles|right-triangle,,,
CLASS_9,MATHEMATICS,Circles,,circle-theorems|circle-radius,,,
CLASS_9,MATHEMATICS,Statistics,,histogram|bar-graph,,,
CLASS_10,MATHEMATICS,Pair of Linear Equations in Two Variables,,linear-equation-graph|coordinate-plane,,,
CLASS_10,MATHEMATICS,Quadratic Equations,,quadratic-parabola|xy-graph,,,
CLASS_10,MATHEMATICS,Triangles,,similar-triangles|right-triangle,,,
CLASS_10,MATHEMATICS,Coordinate Geometry,,coordinate-plane,,,
CLASS_10,MATHEMATICS,Introduction to Trigonometry,,trigonometry-triangle|right-triangle,,,
CLASS_10,MATHEMATICS,Some Applications of Trigonometry,,trigonometry-triangle,,,
CLASS_10,MATHEMATICS,Circles,,circle-theorems|circle-radius,,,
CLASS_10,MATHEMATICS,Areas Related to Circles,,circle-radius,,,
CLASS_10,MATHEMATICS,Statistics,,histogram|bar-graph,,,
CLASS_10,PHYSICS,The Human Eye and the Colourful World,human eye,human-eye|prism-dispersion,,,
CLASS_10,CHEMISTRY,Metals and Non-metals,,electrolysis,,,
CLASS_10,CHEMISTRY,Carbon and Its Compounds,,covalent-bond,,,
CLASS_10,BIOLOGY,Control and Coordination,nervous system,neuron|reflex-arc|human-brain,,,
CLASS_10,BIOLOGY,How Do Organisms Reproduce?,reproduction,flower-structure,,,
CLASS_10,BIOLOGY,Heredity and Evolution,genetics,dna-helix,,,
CLASS_11,PHYSICS,Waves,,wave-transverse,,,
CLASS_11,PHYSICS,Oscillations,,wave-transverse,,,
CLASS_11,CHEMISTRY,Structure of Atom,,atom-bohr,,,
CLASS_11,CHEMISTRY,Chemical Bonding and Molecular Structure,bonding,ionic-bond|covalent-bond,,,
CLASS_11,CHEMISTRY,Classification of Elements and Periodicity,periodic table,periodic-table,,,
CLASS_11,BIOLOGY,Cell: The Unit of Life,cell,animal-cell|plant-cell|cell-diagram,,,
CLASS_11,BIOLOGY,Photosynthesis in Higher Plants,,photosynthesis|leaf,,,
CLASS_11,BIOLOGY,Body Fluids and Circulation,circulatory system,human-heart,,,
CLASS_11,BIOLOGY,Neural Control and Coordination,nervous system,neuron|human-brain,,,
CLASS_11,BIOLOGY,Morphology of Flowering Plants,,flower-structure|leaf|root-structure,,,
CLASS_11,MATHEMATICS,Sets,,venn-diagram,,,
CLASS_11,MATHEMATICS,Straight Lines,,coordinate-plane|linear-equation-graph,,,
CLASS_11,MATHEMATICS,Trigonometric Functions,,trigonometry-triangle,,,
CLASS_11,MATHEMATICS,Conic Sections,,quadratic-parabola,,,
CLASS_12,PHYSICS,Electrostatic Potential and Capacitance,capacitor,capacitor|uniform-field,,,
CLASS_12,PHYSICS,Current Electricity,,circuit-simple|resistors-series|resistors-parallel,,,
CLASS_12,PHYSICS,Magnetism and Matter,,bar-magnet-field,,,
CLASS_12,PHYSICS,Electromagnetic Induction,,em-induction,,,
CLASS_12,PHYSICS,Alternating Current,transformer,transformer,,,
CLASS_12,PHYSICS,Ray Optics and Optical Instruments,ray optics,concave-mirror|convex-mirror|ray-diagram-lens|prism-dispersion|human-eye|glass-slab-refraction,,,
CLASS_12,PHYSICS,Wave Optics,,wave-transverse,,,
CLASS_12,PHYSICS,Atoms,,atom-bohr,,,
CLASS_12,CHEMISTRY,Electrochemistry,,electrolysis,,,
CLASS_12,CHEMISTRY,Chemical Kinetics,,xy-graph,,,
CLASS_12,CHEMISTRY,Biomolecules,,dna-helix,,,
CLASS_12,BIOLOGY,Molecular Basis of Inheritance,dna,dna-helix,,,
CLASS_12,BIOLOGY,Ecosystem,food chain,food-chain,,,
CLASS_12,MATHEMATICS,Three Dimensional Geometry,,coordinate-plane,,,
CLASS_12,MATHEMATICS,Application of Derivatives,,xy-graph,,,`;

export const CBSE_CSV_MAPPINGS: ChapterMapping[] = parseCsv(CSV)
  .map((r) => ({
    key: chapterKey(r.classLevel ?? "", r.subject ?? "", r.chapter ?? ""),
    classLevel: r.classLevel ?? "",
    subject: r.subject ?? "",
    chapter: r.chapter ?? "",
    synonyms: r.synonyms ?? [],
    concepts: r.concepts ?? [],
    keywords: r.keywords ?? [],
    formulas: r.formulas ?? [],
    experiments: r.experiments ?? [],
  }))
  .filter((m) => m.classLevel && m.subject && m.chapter);
