-- Expand curriculum to CBSE Classes 6–12 and additional subjects.
-- Idempotent: safe to re-run.
ALTER TYPE "ClassLevel" ADD VALUE IF NOT EXISTS 'CLASS_6';
ALTER TYPE "ClassLevel" ADD VALUE IF NOT EXISTS 'CLASS_7';
ALTER TYPE "ClassLevel" ADD VALUE IF NOT EXISTS 'CLASS_8';
ALTER TYPE "ClassLevel" ADD VALUE IF NOT EXISTS 'CLASS_9';

ALTER TYPE "Subject" ADD VALUE IF NOT EXISTS 'SCIENCE';
ALTER TYPE "Subject" ADD VALUE IF NOT EXISTS 'SOCIAL_SCIENCE';
ALTER TYPE "Subject" ADD VALUE IF NOT EXISTS 'COMPUTER_SCIENCE';
ALTER TYPE "Subject" ADD VALUE IF NOT EXISTS 'HINDI';
ALTER TYPE "Subject" ADD VALUE IF NOT EXISTS 'SANSKRIT';
